# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage
lang: en

# Change to your timezone
timezone: America/Denver

# jekyll-seo-tag settings
title: Jojo's Projects

tagline: Innovative AI solutions and personal experiments

description: >-
  Showcasing my portfolio of AI-powered projects, from automation tools to intelligent dispatch systems.

# Fill in the protocol & hostname for your site.
url: "https://jmcdice.github.io" # Update this to your actual GitHub pages URL

github:
  username: jmcdice

twitter:
  username: jmcdice

social:
  name: Joey 
  email: jmcdice@gmail.com
  links:
    - https://twitter.com/jmcdice
    - https://github.com/jmcdice

# Site Verification Settings
webmaster_verifications:
  google: # fill in your Google verification code
  bing: 
  alexa: 
  yandex: 
  baidu: 
  facebook: 

# Web Analytics Settings
analytics:
  google:
    id: # fill in your Google Analytics ID
  goatcounter:
    id: 
  umami:
    id: 
    domain: 
  matomo:
    id: 
    domain: 
  cloudflare:
    id: 
  fathom:
    id: 

# Page views settings
pageviews:
  provider: goatcounter

# Prefer color scheme setting
theme_mode: dark

# CDN endpoint for media resources
cdn: 

# Avatar for sidebar
avatar: /common/profile.png

# URL for social preview image
social_preview_image: 

# TOC in posts
toc: true

comments:
  provider: disqus
  disqus:
    shortname: jojo-ai-projects

# Self-hosted static assets
assets:
  self_host:
    enabled: false

pwa:
  enabled: true
  cache:
    enabled: true

paginate: 10

# Base URL of the site
baseurl: ""

# Additional configurations below
kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

